language: ruby
cache: bundler
sudo: false

rvm:
- 2.0.0
- 2.1
- 2.2

branches:
  only:
    - master

notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: "z33TKM67IPl+SUP9YZzZ3bl5384xrF8lm/PEdPmL9cGVJDLxN6VVo3hfwz//NlavS0Dfth4Y1Cb2c4cWqixpLNKaxcVZqulDx4ap13y1sSAmsN072hH5nsgHiF4NaqomUY0ytSudS3NOVUiXddGMALwZI0iinU3jKPKMXEy+ttwyd1Agetc7ZuNxEVf941jzaMrnyrHEU6DQnrfG5eR76XAB6fJaiMdFkfGN9d703prQzKF8YBL+5gNqtS9B4yaJbZ60RTiWPjU2lmPeLkWAohJwohbhRd2c5AbSsDTC6ZqcmHWCeI6emrWW9BqMT6atbgIyDkPYBbuWi5yyzGTAlYQC5RpaHlgK/Y5LlsxN05SHA059x1iC20s9E5F6TbQ08o3Yv2480tq9XEOTyJUPN5OFGLLlHGWTNpzfJBdRtPI44mw94ZMIowaPtpeEUIL5B6WfMIuM63wOkX1gBicv3LXAwYTKPyeNGH2ZTNVFc1EeRwgcaxhJaY73RJ9uKT8b09J1qteAKNuCVhuW4MXwDkYmJr8N/sZXLTrl+nwDYMSf+RxjMCsx7Z1C4rg9OuOT4M4vl/L72zoq3pwy2ZMOpPgYasyJtRzPRwKwYrw2UZ0iApWDyON/NXzFR0GK8jpCgoCnwjTRvAw7PpkNhJdIB1hFhqUsQCeQPALip3cAOMI="
